#include "FLMCUSwitch.h"

#if (FLSYSTEM_ENABLE_THREADLIB == 0)
#define FLSYSTEM_ENABLE_DEFAULT_LIBRARY
#define FLSYSTEM_3RD_THREAD
#elif (FLSYSTEM_ENABLE_THREADLIB == 1)
#define FLSYSTEM_ENABLE_FREERTOS_LIBRARY
#define FLSYSTEM_3RD_FREERTOS
#elif (FLSYSTEM_ENABLE_THREADLIB == 2)
#ifndef FLSYSTEM_SET_CUSTOM_TRANSPLANTATION
#ifdef FLSYSTEM_UNKNOW_BOARD
#define FLSYSTEM_ENABLE_DEFAULT_LIBRARY
#define FLSYSTEM_3RD_THREAD
#else
#define FLSYSTEM_ENABLE_FREERTOS_LIBRARY
#define FLSYSTEM_3RD_FREERTOS
#endif
#else
#define FLSYSTEM_ENABLE_CUSTOM_TRANSPLANTATION
#endif
#endif

#include "3rdInclude.h"